[package]
name="ERC4626"
version="0.1.5"

[addresses]
ERC4626="_"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'
